import React from 'react';

// Placeholder for Lucide icons if not directly imported in this environment
const Icon = ({ name, className }) => {
  const getIconSvg = (iconName) => {
    switch (iconName) {
      case 'BookOpen':
        return (
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
            <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path>
            <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path>
          </svg>
        );
      case 'Lightbulb':
        return (
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
            <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1.3.5 2.6 1.5 3.5.8.8 1.3 1.5 1.5 2.5"></path>
            <path d="M9 18h6"></path>
            <path d="M10 22h4"></path>
            <path d="M12 22v-4"></path>
          </svg>
        );
      case 'Pyramid':
        return (
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
            <path d="M2.5 17.5L12 2L21.5 17.5L12 22L2.5 17.5Z"></path>
            <path d="M12 2v20"></path>
            <path d="M5 12l7-10l7 10"></path>
          </svg>
        );
      case 'ScrollText':
        return (
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
            <path d="M8 21h8a2 2 0 0 0 2-2V7H6v12a2 2 0 0 0 2 2z"></path>
            <path d="M14.5 5.5L12 3L9.5 5.5"></path>
            <path d="M12 3v4"></path>
            <path d="M8 11h8"></path>
            <path d="M8 15h8"></path>
          </svg>
        );
      case 'HeartHandshake':
        return (
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
            <path d="M11 14H7a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l3 3h2a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-4l-3-3z"></path>
            <path d="M12 11l-3 3"></path>
            <path d="M15 14l-3 3"></path>
            <path d="M17 17l-3 3"></path>
            <path d="M19 20l-3 3"></path>
            <path d="M22 17l-3 3"></path>
            <path d="M22 14l-3 3"></path>
            <path d="M12 11l-3 3"></path>
          </svg>
        );
      default:
        return null;
    }
  };
  return getIconSvg(name);
};


function App() {
  return (
    <div className="min-h-screen bg-gray-50 font-inter text-gray-800">
      {/* Meta Description for SEO */}
      <meta name="description" content="Per-Ankh: House of Life and Knowledge. Explore ancient Egyptian wisdom through our educational resources, learning programs, and research projects." />

      {/* Tailwind CSS CDN */}
      <script src="https://cdn.tailwindcss.com"></script>

      {/* Header */}
      <header className="bg-white shadow-sm py-4 px-6 md:px-12 rounded-b-lg">
        <nav className="container mx-auto flex justify-between items-center">
          <div className="flex items-center space-x-2">
            <Icon name="Pyramid" className="h-8 w-8 text-amber-600" />
            <h1 className="text-3xl font-bold text-gray-900">Per-Ankh</h1>
          </div>
          <ul className="hidden md:flex space-x-8">
            <li><a href="#home" className="text-lg font-medium text-gray-700 hover:text-amber-600 transition duration-300">Home</a></li>
            <li><a href="#about" className="text-lg font-medium text-gray-700 hover:text-amber-600 transition duration-300">About Us</a></li>
            <li><a href="#services" className="text-lg font-medium text-gray-700 hover:text-amber-600 transition duration-300">Services</a></li>
            <li><a href="#contact" className="text-lg font-medium text-gray-700 hover:text-amber-600 transition duration-300">Contact</a></li>
          </ul>
          {/* Mobile Menu Button (Hamburger) */}
          <button className="md:hidden p-2 rounded-md text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-amber-500">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16m-7 6h7"></path>
            </svg>
          </button>
        </nav>
      </header>

      {/* Hero Section */}
      <section id="home" className="relative bg-gradient-to-br from-amber-500 to-amber-700 text-white py-20 md:py-32 rounded-b-lg shadow-lg">
        <div className="container mx-auto text-center px-6">
          <h2 className="text-4xl md:text-6xl font-extrabold leading-tight mb-6 animate-fade-in-down">
            Welcome to <span className="text-yellow-200">Per-Ankh</span>
          </h2>
          <p className="text-xl md:text-2xl mb-10 opacity-90 animate-fade-in-up">
            The House of Life and Knowledge at the heart of ancient Egyptian civilization. Discover wisdom, expand learning, and engage in research.
          </p>
          <a href="#about" className="inline-block bg-white text-amber-700 hover:bg-gray-100 px-8 py-3 rounded-full text-lg font-semibold shadow-lg transform hover:scale-105 transition duration-300 ease-in-out">
            Explore More
          </a>
        </div>
      </section>

      {/* About Section - Story Integrated */}
      <section id="about" className="py-16 md:py-24 bg-white rounded-lg shadow-md mx-4 md:mx-auto my-8 max-w-6xl">
        <div className="container mx-auto px-6">
          <h3 className="text-4xl font-bold text-center text-gray-900 mb-12">
            What is <span className="text-amber-600">Per-Ankh</span>?
          </h3>
          <div className="flex flex-col md:flex-row items-center md:space-x-12">
            <div className="md:w-1/2 mb-8 md:mb-0">
              <img
                src="https://placehold.co/600x400/FDBA74/8B5CF6?text=Ancient+Egypt"
                alt="Ancient Egyptian Scene"
                className="rounded-lg shadow-xl w-full h-auto object-cover"
                onError={(e) => { e.target.onerror = null; e.target.src = 'https://placehold.co/600x400/FDBA74/8B5CF6?text=Ancient+Egypt'; }}
              />
            </div>
            <div className="md:w-1/2 text-lg text-gray-700 leading-relaxed">
              <p className="mb-4">
                In ancient Egypt, the <strong className="text-amber-600">"Per-Ankh"</strong>, or <strong className="text-amber-600">"House of Life"</strong>, was a central institution for knowledge and learning. It was not merely a place for storing books and scrolls, but a vibrant center where medicine, astronomy, mathematics, writing, and philosophy were taught.
              </p>
              <p className="mb-4">
                Scribes, priests, and scholars worked together in these houses, copying ancient texts, creating new works, and preserving the rich cultural heritage of Egyptian civilization. These institutions served as universities, libraries, and research centers all at once.
              </p>
              <p className="mb-4">
                Our goal at <strong className="text-amber-600">Per-Ankh</strong> is to revive this concept, offering a modern platform for knowledge and learning, inspired by ancient wisdom and contemporary progress.
              </p>
              <h4 className="text-2xl font-semibold text-gray-900 mb-4">The Story Behind Per-Ankh</h4>
              <p className="mb-4">
                "My father was a political science professor and had a huge library with more than 5,000 books that was left in dust as we, his family, didn't use this library as we all went through different directions in different fields.
              </p>
              <p className="mb-4">
                The inspiration deepened when I was working on an initiative called "Exchange your book." We received a call from a donor with over 1000 books, all packed in boxes. While the books were rich in content, they were unfortunately wet and dusty, having been left neglected in an open area. This experience solidified the idea for a research center.
              </p>
              <p>
                At Per-Ankh, we will call for donors with large libraries to contribute their books to our center. The center will also feature a computer lab, business hub, meeting and conference rooms, and a reading area, designed to help everyone—from those seeking specific research materials to general readers—find what they need easily. We believe that knowledge is power, and it should be available to everyone. Our mission is to revive the spirit of the ancient House of Life, creating a global community where curiosity thrives, and ideas flourish. Join us in building a future where knowledge knows no bounds, and every mind has the opportunity to shine."
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Services Section */}
      <section id="services" className="py-16 md:py-24 bg-gray-100 rounded-lg shadow-md mx-4 md:mx-auto my-8 max-w-6xl">
        <div className="container mx-auto px-6">
          <h3 className="text-4xl font-bold text-center text-gray-900 mb-12">
            What We Offer at <span className="text-amber-600">Per-Ankh</span>
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Service Card 1 */}
            <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition duration-300 transform hover:-translate-y-2 text-center">
              <Icon name="BookOpen" className="h-16 w-16 text-amber-600 mx-auto mb-6" />
              <h4 className="text-2xl font-semibold text-gray-900 mb-4">Knowledge Resources</h4>
              <p className="text-gray-700">
                A rich digital library of ancient and modern texts and manuscripts to expand your intellectual horizons.
              </p>
            </div>
            {/* Service Card 2 */}
            <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition duration-300 transform hover:-translate-y-2 text-center">
              <Icon name="Lightbulb" className="h-16 w-16 text-amber-600 mx-auto mb-6" />
              <h4 className="text-2xl font-semibold text-gray-900 mb-4">Educational Programs</h4>
              <p className="text-gray-700">
                Courses and workshops in various fields, inspired by ancient and modern learning methodologies.
              </p>
            </div>
            {/* Service Card 3 */}
            <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition duration-300 transform hover:-translate-y-2 text-center">
              <Icon name="ScrollText" className="h-16 w-16 text-amber-600 mx-auto mb-6" />
              <h4 className="text-2xl font-semibold text-gray-900 mb-4">Research & Development</h4>
              <p className="text-gray-700">
                Support for research projects aimed at uncovering the secrets of ancient civilizations and applying them in the modern era.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Call to Action Section */}
      <section className="bg-amber-600 text-white py-16 md:py-20 text-center rounded-lg shadow-md mx-4 md:mx-auto my-8 max-w-6xl">
        <div className="container mx-auto px-6">
          <h3 className="text-4xl font-bold mb-6">Join the Journey of Knowledge</h3>
          <p className="text-xl mb-8 opacity-90">
            Be part of the Per-Ankh community and explore new worlds of wisdom.
          </p>
          <a href="#contact" className="inline-block bg-white text-amber-700 hover:bg-gray-100 px-8 py-3 rounded-full text-lg font-semibold shadow-lg transform hover:scale-105 transition duration-300 ease-in-out">
            Contact Us
          </a>
        </div>
      </section>

      {/* Footer */}
      <footer id="contact" className="bg-gray-900 text-gray-300 py-10 rounded-t-lg">
        <div className="container mx-auto px-6 text-center">
          <div className="mb-6">
            <h5 className="text-2xl font-semibold text-white mb-3">Per-Ankh</h5>
            <p className="text-sm">House of Life and Knowledge</p>
          </div>
          <div className="flex justify-center space-x-6 mb-6">
            <a href="#" className="text-gray-400 hover:text-amber-500 transition duration-300">
              <Icon name="HeartHandshake" className="h-6 w-6" />
            </a>
            {/* Add more social media icons if needed */}
          </div>
          <p className="text-sm">&copy; {new Date().getFullYear()} Per-Ankh. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}

export default App;
.
